# Generated by Django 3.2.15 on 2023-02-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk'], 'permissions': [('change_own_user', 'Can change own user')]},
        ),
    ]
