# Generated by Django 3.2.15 on 2023-03-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_menupermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermissions',
            options={'permissions': [('user_view_main', 'Menu Can view user main menu'), ('user_view_list_users', 'Menu Can view list of users'), ('user_create_user', 'Menu Can create a new user'), ('user_show_my_user', 'Menu Can view own user'), ('company_view_main', 'Menu Can view company main menu'), ('company_view_list_companies', 'Menu Can view list of companies'), ('company_create_company', 'Menu Can create a new company'), ('company_delete_a_company', 'Menu Can delete a company'), ('companygroup_view_list', 'Menu Can view company group list'), ('commodity_view_list', 'Menu Can view commodity list'), ('actortype_view_list', 'Menu Can view actortype list'), ('company_validation_view_list', 'Menu Can view company validation list'), ('company_verification_view_list', 'Menu Can view company verification list'), ('company_list_company_validation_list', 'Menu Can view list of company to validate'), ('company_list_company_verify_list', 'Menu Can view list of company to verify'), ('bankquestion_view_main', 'Menu Can view bankquestion main menu'), ('bankquestion_view_list_bankquestions', 'Menu Can view list of bankquestion'), ('bankquestion_view_list_categories', 'Menu Can view list of categories'), ('bankquestion_view_list_subcategories', 'Menu Can view list of subcategories'), ('bankquestion_view_list_topics', 'Menu Can view list of topics'), ('formularios_view_main', 'Menu Can view formularios main menu'), ('formularios_assign_formularios_list', 'Menu Can view formularios menu to asign'), ('formularios_assign_formularios_validator', 'Menu Can view formularios menu to asign validator'), ('formularios_assign_formularios_verificator', 'Menu Can view formularios menu to asign verificator'), ('formularios_view_results_list', 'Menu Can view formularios results'), ('formularios_list_formularios_to_validate', 'Menu Can view formularios list to validate'), ('formularios_list_formularios_to_verify', 'Menu Can view formularios list to verify'), ('supplybase_view_main', 'Menu Can view supplybase main menu'), ('supplybase_view_list', 'Menu Can view supplybase list'), ('supplybase_assign_supplybase_validator', 'Menu Can view supplybase menu to asign validator'), ('supplybase_assign_supplybase_verificator', 'Menu Can view supplybase menu to asign verificator'), ('supplybase_view_supplybase_resume_list', 'Menu Can view resume of supplybase results'), ('supplybase_list_supplybase_to_validate', 'Menu Can view supplybase list to validate'), ('supplybase_list_supplybase_to_verify', 'Menu Can view supplybase list to verify')]},
        ),
    ]
