# Generated by Django 3.2.15 on 2023-03-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_menupermissions_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPermissions',
        ),
    ]
