# Generated by Django 3.2.15 on 2023-01-19 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(blank=True, max_length=126, null=True)),
                ('supplier_tax_number', models.CharField(blank=True, max_length=126, null=True)),
                ('supplier_capacity', models.FloatField(blank=True, null=True)),
                ('supplier_production', models.FloatField(blank=True, null=True)),
                ('purchased_volume', models.FloatField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=126, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('period', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('status_revision', models.CharField(choices=[('SR', 'Self Reported'), ('NV', 'Not Validated'), ('VA', 'Validated'), ('NVE', 'Not Verified'), ('VE', 'Verified')], default='SR', max_length=3)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TraceabilityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_traceability', models.FileField(upload_to='traceabilityfiles/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='ValidateTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('status_revision', models.CharField(max_length=3)),
            ],
            options={
                'permissions': [('assign_validation_traceability', 'Can Assign Validation Traceability')],
            },
        ),
        migrations.CreateModel(
            name='VerifyTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('status_revision', models.CharField(max_length=3)),
            ],
            options={
                'permissions': [('assign_verification_traceability', 'Can Assign Validation Traceability')],
            },
        ),
    ]
