# Generated by Django 3.2.15 on 2023-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validatetraceability',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verifytraceability',
            options={},
        ),
    ]
