# Generated by Django 3.2.15 on 2023-01-26 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traceability', '0003_auto_20230120_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='validator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validator_traceability', to=settings.AUTH_USER_MODEL),
        ),
    ]
