# Generated by Django 3.2.15 on 2023-01-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0004_traceability_validator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='deadline_validation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
