# Generated by Django 3.2.15 on 2023-01-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0005_traceability_deadline_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceability',
            old_name='deadline_validation',
            new_name='end_date_validation',
        ),
        migrations.AddField(
            model_name='traceability',
            name='start_date_validation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
