# Generated by Django 3.2.15 on 2023-03-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0007_auto_20230222_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traceability',
            options={'ordering': ['-pk'], 'permissions': [('export_traceability', 'Can export traceability')]},
        ),
    ]
