# Generated by Django 3.2.15 on 2023-03-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('token_type', models.CharField(max_length=126)),
                ('expires_in', models.IntegerField()),
                ('access_token', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
