# Generated by Django 3.2.15 on 2023-03-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(),
        ),
    ]
