# Generated by Django 3.2.15 on 2023-03-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedrive', '0002_alter_token_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
