# Generated by Django 3.2.15 on 2023-01-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycompany',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verifycompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AddField(
            model_name='validatecompany',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validatecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AddField(
            model_name='companyuserformkey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='actor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.actortype'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion'),
        ),
        migrations.AddField(
            model_name='company',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.commodity'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.companygroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='company',
            name='validator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actortype',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actor_type', to='company.commodity'),
        ),
    ]
