# Generated by Django 3.2.15 on 2023-01-19 12:03
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
