# Generated by Django 3.2.15 on 2023-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20230119_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validatecompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verifycompany',
            options={},
        ),
    ]
