# Generated by Django 3.2.15 on 2023-01-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_actortype_is_productor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validatecompany',
            options={'permissions': [('assign_validation_company', 'Can assign validation company')]},
        ),
        migrations.AlterModelOptions(
            name='verifycompany',
            options={'permissions': [('assign_verification_company', 'Can assign verification company')]},
        ),
    ]
