# Generated by Django 3.2.15 on 2023-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20230203_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
