# Generated by Django 3.2.15 on 2023-03-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20230222_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status_revision',
            field=models.CharField(blank=True, choices=[('SR', 'Self Reported'), ('NV', 'Not Validated'), ('VA', 'Validated'), ('NVE', 'Not Verified'), ('VE', 'Verified')], default='SR', max_length=3, null=True),
        ),
    ]
