# Generated by Django 3.2.15 on 2023-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_commodity_drive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actortype',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
