# Generated by Django 3.2.15 on 2023-03-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsbank', '0001_initial'),
        ('company', '0015_auto_20230316_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='drive_folder_category_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='drive_folder_subcategory_id',
        ),
        migrations.CreateModel(
            name='QuestionDriveSubCategoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('drive_folder_subcategory_id', models.CharField(blank=True, max_length=126, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionDriveCategoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('drive_folder_category_id', models.CharField(blank=True, max_length=126, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
