# Generated by Django 3.2.15 on 2023-01-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionsbank', '0001_initial'),
        ('proforestform', '0001_initial'),
        ('company', '0001_initial'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_question_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.question'),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulario.formulario'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.questionbank'),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulario',
            name='allocating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocating_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='assigned_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='bank_questions',
            field=models.ManyToManyField(to='questionsbank.QuestionBank'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulario',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proforestform.period'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='proforestform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proforestform.proforestform'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisor_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
