# Generated by Django 3.2.15 on 2023-01-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('status_revision', models.CharField(max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='ValidateFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('status_revision', models.CharField(max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.formulario')),
            ],
        ),
    ]
