# Generated by Django 3.2.15 on 2023-01-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20230123_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='deadline_revision',
            new_name='end_date_validation',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='days_of_revision',
        ),
        migrations.AddField(
            model_name='formulario',
            name='start_date_validation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='revision_status',
            field=models.CharField(choices=[('VERIFIED', 'verified'), ('INVERIFYPROCESS', 'in verify process'), ('WITHOUTVERIFY', 'Without verify'), ('VALIDATE', 'validated'), ('INVALIDATINGPROCESS', 'in validadtion process'), ('WITHOUTVALIDATE', 'Without validate')], default='WITHOUTCHECK', max_length=64),
        ),
    ]
