# Generated by Django 3.2.15 on 2023-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20230130_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='revision_status',
            field=models.CharField(choices=[('VERIFIED', 'verified'), ('INVERIFYPROCESS', 'in verify process'), ('WITHOUTVERIFY', 'Without verify'), ('VALIDATE', 'validated'), ('INVALIDATINGPROCESS', 'in validadtion process'), ('WITHOUTVALIDATE', 'Without validate'), ('NOTASSIGNED', 'Not Asigned')], default='NOTASSIGNED', max_length=64),
        ),
    ]
