# Generated by Django 3.2.15 on 2023-02-02 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0006_alter_formulario_revision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulario_answer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='validation',
            field=models.CharField(choices=[('ARE', 'Autoreported answer'), ('VAL', 'Validated answer'), ('NVA', 'Not validated answer'), ('VER', 'Verified answer'), ('NVE', 'Not Verified answer')], default='ARE', max_length=3),
        ),
    ]
