# Generated by Django 3.2.15 on 2023-02-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20230201_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='status_form',
            field=models.CharField(choices=[('NOTVISIBLE', 'Not visible form'), ('ACTIVE', 'Active Form'), ('FINISHED', 'Finished Form'), ('CLOSED', 'Closed Form')], default='NOTVISIBLE', max_length=16),
        ),
    ]
