# Generated by Django 3.2.15 on 2023-02-22 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0008_alter_formulario_status_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='revisor',
        ),
        migrations.AddField(
            model_name='formulario',
            name='revisor',
            field=models.ManyToManyField(blank=True, related_name='revisor_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
