# Generated by Django 3.2.15 on 2023-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_auto_20230222_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='active_next_period',
            field=models.BooleanField(default=True),
        ),
    ]
