# Generated by Django 3.2.15 on 2023-01-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=126, unique=True)),
                ('name_es', models.CharField(max_length=126, unique=True)),
                ('name_pt', models.CharField(max_length=126, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=126)),
                ('name_es', models.CharField(max_length=126)),
                ('name_pt', models.CharField(max_length=126)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='questionsbank.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=126)),
                ('name_es', models.CharField(max_length=126)),
                ('name_pt', models.CharField(max_length=126)),
                ('code', models.CharField(max_length=126, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic', to='questionsbank.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('question_data', models.JSONField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.subcategory')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionsbank.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
