# Generated by Django 3.2.15 on 2023-01-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplybase', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplybaseregister',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplybasedependency',
            name='actor_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='actortype_buyer', to='company.actortype'),
        ),
        migrations.AddField(
            model_name='supplybasedependency',
            name='actor_type_dependency',
            field=models.ManyToManyField(to='company.ActorType'),
        ),
        migrations.AddField(
            model_name='supplybase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplybase_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='supplybase',
            name='supplier_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplybase_supplier_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='purchasedpercentage',
            name='actor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_actortype', to='company.actortype'),
        ),
        migrations.AddField(
            model_name='purchasedpercentage',
            name='supplybase_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplybase.supplybaseregister'),
        ),
    ]
