# Generated by Django 3.2.15 on 2023-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplybase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpercentage',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
