# Generated by Django 3.2.15 on 2023-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforestform', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforestform',
            name='exclusion_logic_group',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
