# Generated by Django 3.2.15 on 2023-01-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforestform', '0004_proforestform_name_of_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proforestform',
            old_name='name_of_group',
            new_name='name_group',
        ),
    ]
