# Generated by Django 3.2.15 on 2023-02-14 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_has_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proforestform', '0006_proforestform_company_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforestform',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='User_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proforestform',
            name='company_assigned',
            field=models.ManyToManyField(blank=True, related_name='Company_assigned', to='company.Company'),
        ),
    ]
